---
version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
  openb:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
  api:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile
